#!/bin/sh

first_line=$(sed -n '1p' "$1")

echo "$first_line" | grep -Eq '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([^)]+\))?(!)?: .+' || {
  echo "Commit message moet Conventional Commits volgen, bv. feat:, fix:, docs:, chore:, ..."
  exit 1
}
